### PR TITLE
test: refresh VPCSC tests

### PR DESCRIPTION
**Pull request by steinwaywhw**
Refresh VPCSC tests to cover AgentTranslationService/CollectdTimeSeries endpoint.

### CODE REVIEW

**Comment by steinwaywhw** [comment]
@chingor13 Hi Jeff, the dependency failure is due to a dependency on come.google.auth:google-auth-library-oauth2-http. Could you advise on how to add this dependency?

**Comment by chingor13** [comment]
For the dependencies test failure, you'll want to add:

```xml
<dependency>
  <groupId>com.google.auth</groupId>
  <artifactId>google-auth-library-oauth2-http</artifactId>
  <version>0.20.0</version>
  <scope>test</scope>
</dependency>
```

to the `<dependencies>` section of `google-cloud-monitoring/pom.xml`

**Comment by steinwaywhw** [comment]
Thanks!

**Comment by chingor13** [comment]
Sorry, 0.20.0 is having dependency issues (until we can update guava), 0.19.0 fixes it

**Pull request merged**
